language: node_js
node_js:
  - '12'
  - node
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

before_script:
  - yarn install
script:
  - yarn test-ci
